name:
  pos1:
    ==: org.bukkit.Location
    world: world
    x: -662.0
    y: 3.0
    z: -49.0
    pitch: 0.0
    yaw: 0.0
  pos2:
    ==: org.bukkit.Location
    world: world
    x: -632.0
    y: 35.0
    z: -23.0
    pitch: 0.0
    yaw: 0.0
  min: 0
  max: 1
